trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
    sh init.sh -y
    echo "##vso[task.prependpath]/home/vsts/.nimble/bin:$PATH"
  displayName: Install nim toolchain
- bash: make build-release
  displayName: Compile (release)
