trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: |
    curl https://nim-lang.org/choosenim/init.sh -sSf -o init.sh
    sh init.sh -y
    echo "##vso[task.prependpath]/home/vsts/.nimble/bin:$PATH"
  displayName: Install nim toolchain
- bash: sudo apt install -y mingw-w64
  displayName: Install MinGW
- bash: make build-release-linux
  displayName: Build release build (Linux)
- bash: make build-release-win
  displayName: Build release build (Windows)
- bash: |
    cp whereami_linux $(Build.ArtifactStagingDirectory)/whereami
    cp whereami_win $(Build.ArtifactStagingDirectory)/whereami.exe
  displayName: Move build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: binaries
