name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.9]
        os: [windows-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      if: runner.os != 'Windows'
    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
    - name: Build
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: whereami-${{ matrix.os }}
        path: whereami
      
      
      
      
      
      
      
      
