name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: nimlang/nim
      
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: |
        apt update
        apt install make -y
    - name: Release build
      run: make build-release
